apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIGatewayRoute
metadata:
  name: default-model
  namespace: inference
spec:
  hostnames:
    - ai.zer0.garden
  parentRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
      namespace: envoy-ai-gateway-system
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: default
      modelsOwnedBy: enki.stack
      backendRefs:
        - name: default-backend
