apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: default-backend
  namespace: inference
spec:
  schema:
    name: OpenAI
  backendRef:
    name: default-predictor
    kind: Backend
    group: gateway.envoyproxy.io
