apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-ai-gateway.yaml
  - namespace-observability.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: enki-infer
      app.kubernetes.io/managed-by: kustomize
